Invoking command in '/home/ubuntu/cu-arc-21-22/CS/drone_ws/src/ros2_pi_gpio/pi_gpio': PYTHONPATH=/home/ubuntu/cu-arc-21-22/CS/drone_ws/install/pi_gpio/lib/python3.8/site-packages:/home/ubuntu/cu-arc-21-22/CS/drone_ws/install/pi_gpio_interface/lib/python3.8/site-packages:/home/ubuntu/cu-arc-21-22/CS/drone_ws/install/pi_gpio/lib/python3.8/site-packages:/home/ubuntu/cu-arc-21-22/CS/drone_ws/install/controls/lib/python3.8/site-packages:/home/ubuntu/ros2_foxy/ros2-linux/lib/python3.8/site-packages /usr/bin/python3 setup.py egg_info --egg-base ../../../build/pi_gpio build --build-base /home/ubuntu/cu-arc-21-22/CS/drone_ws/build/pi_gpio/build install --prefix /home/ubuntu/cu-arc-21-22/CS/drone_ws/install/pi_gpio --record /home/ubuntu/cu-arc-21-22/CS/drone_ws/build/pi_gpio/install.log --single-version-externally-managed
Invoked command in '/home/ubuntu/cu-arc-21-22/CS/drone_ws/src/ros2_pi_gpio/pi_gpio' returned '0': PYTHONPATH=/home/ubuntu/cu-arc-21-22/CS/drone_ws/install/pi_gpio/lib/python3.8/site-packages:/home/ubuntu/cu-arc-21-22/CS/drone_ws/install/pi_gpio_interface/lib/python3.8/site-packages:/home/ubuntu/cu-arc-21-22/CS/drone_ws/install/pi_gpio/lib/python3.8/site-packages:/home/ubuntu/cu-arc-21-22/CS/drone_ws/install/controls/lib/python3.8/site-packages:/home/ubuntu/ros2_foxy/ros2-linux/lib/python3.8/site-packages /usr/bin/python3 setup.py egg_info --egg-base ../../../build/pi_gpio build --build-base /home/ubuntu/cu-arc-21-22/CS/drone_ws/build/pi_gpio/build install --prefix /home/ubuntu/cu-arc-21-22/CS/drone_ws/install/pi_gpio --record /home/ubuntu/cu-arc-21-22/CS/drone_ws/build/pi_gpio/install.log --single-version-externally-managed
